### PR TITLE
feat(application) add CronJob capability

### PR DESCRIPTION
**Pull request by knabben-mms**

### CODE REVIEW

**Review by heubeck — DISMISSED** [review]

**Comment by stuebingerb** [comment]
How is this different from the existing metronome? Does it replace that chart?

**Comment by stuebingerb** [comment]
Also, with the recent modifications I'm doubting that this is still a "Generic application chart with common requirements of a typical workload.".

Maybe we want to restructure the charts?

**Comment by heubeck** [comment]
> How is this related to the existing metronome? Does it replace that chart? Why would someone use this over the other? Can we have some documentation?

The metronom keeps an specialized chart for triggering arbitrary http endpoints.

This change is about being able to run also complex jobs, including volume mounts, init containers and setup phases - we decided to not build an own chart, cause the requirements of the use-case that triggered that change requires most of the features already built in here.

**Comment by heubeck** [comment]
> Also, with the recent modifications I doubt that this is still a "**Generic** application chart with **common** requirements of a **typical** workload.".
> 
> Maybe we want to restructure the charts? At least from Proco side I am considering moving away from the application chart because I don't need any of those additions and they unnecessarily increase the complexity and risk of failure.

Yes, we reached a point where we should restructure and come up with a new major version also cleaning up some hassles in that chart.

I'm some kiss-like charts in mind that can be combined together in composite charts using the dependency mechanism.

If you're not confident to continue to use the chat, I would appreciate to put your efforts in helping to build the next-gen chart(s) for the benefit of all.

**Pull request merged**
